<a href="https://colab.research.google.com/github/AdshayaniPirapaharan/ADBMS/blob/master/Tute_1.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [7]:
x=12
print(type(x))

name="Shubha"
print(type(name))  

flag=True
print(type(flag))

cars=["Honda","Toyota", "Suzuki"]
values=[1,2,3,4,5]
print(type(cars))

days = ("Sunday","mon","tue","wed","thur","fri","sat","sun")
print(type(days))

day2={1:"sunday", 2:"Monday"}
print(type(day2))



<class 'int'>
<class 'str'>
<class 'bool'>
<class 'list'>
<class 'tuple'>
<class 'dict'>


#operators



```

#Arithmatic operators : + , - ,* ,/ (integer division)),% , **(exponent) 
#Logical operators : and, or, not
#Comparison : ==,!=,>,<,>=,<=
#Assignment : =,+=, -=,*=,/=,%=,**=
#Membership : in, not in
```





In [5]:
days=("sun","mon","tue","wed", "thur")
value = [1,2,3,4,5]
exists = "sun" not in days
available = 1 in value
print(exists,available)


False True


## Conditional Statements : if statement, if-else statement, nested if statement

In [9]:
x=5
if (x>10):
  print("I'm inside the IF condition")
  print("Hello")
else:
  print("I'm in the else condition")
print("I'm outside the IF condition")

I'm in the else condition
I'm outside the IF condition


In [10]:
#Nested IF Condition
''' Group comment
in java -------
if(x<5){
  print("x is less than 5")
  }
else if(x<10){
  print("x is less than 10")
  }
else{
  print("x is greater than 10")
  }
------- '''

if(x<5):
  print("x is less than 5")
elif(x<10):
  print("x is less than 10")
else:
  print("x is greater than 10")



x is less than 10


In [16]:
#Iteration Statement For, While

val=[1,2,3,4,5]
'''
for(int i=0:i<val.size(),++i){
  print(val[i]
}


while(i<items.length()) {
  print(itam[i])
  i=i+1
}
'''

range(5) #[0,1,2,3,4]
items=range(5)
for i in items:
  print(i)
itam=list(range(5))
print(itam)
i=0
while i<len(itam):
  print(itam[i])
  i=i+1

# i is autoincremented withi for loop unlike while
#mostly try to use for loops rather than while loop

0
1
2
3
4
[0, 1, 2, 3, 4]
0
1
2
3
4


### Remember For loop and Condtional statement identations. That is enough for now. 

## **Functional Language Concepts**

In [20]:
#Define Fuctions in java : <accessmodifier  returntype  function_name(arguments)>
#in Python
def funcInit(x):
  print("My First Function")
  if (x<10):
    print("X is less than 10")
  else:
    print("X is greater than 10")
  return "subha"



#print("not indented, so i'm outside function")
name=funcInit(6)
print(name)
  


My First Function
X is less than 10
subha


# **Numpy Arrays**

numerical python

In [32]:
import numpy as np  
#numpy is computationally and memory wise much faster, efficient and easy in mulidimensional arrays
''' therefore computations, comparisons  are much faster
efficient implementation of list
therefore we used in machine learning etc. 
'''
num_list = [10,11,12,13,14]
num_array=np.array(num_list)
type(num_list),type(num_array), num_array.shape

#Merge couple of python lists into one numpy array
list1=[10,12,13,14]
list2=[15,16,17,18]
list3=[45,32,10,21]
num_array_2D = np.array([list1,list2,list3])
num_array_2D.shape   #produces 2D Array of 3 rows and 4 columns. this statement shows the shape/dimentions


values = np.arange(0,5) #=range(5)
print(values,type(values), values.shape)

print("\n")


print("One  arrays")
#how to create array of ones
ones_np_array = np.ones(6)
print(ones_np_array, ones_np_array.shape)

ones_np_2Darray = np.ones((6,5))
print(ones_np_2Darray, ones_np_2Darray.shape)
print("\n")

print("Zero arrays")
#how to create array of zeros
zeros_np_array = np.zeros(3)
print(ones_np_array, ones_np_array.shape)

zeros_np_3Darray = np.zeros((6,5,4))   #6=no.of2d arrays(rows,columns), 5=no.of rows of 2d array, 4= no.of columns of 2d array
print(zeros_np_3Darray, zeros_np_3Darray.shape)

[0 1 2 3 4] <class 'numpy.ndarray'> (5,)


One  arrays
[1. 1. 1. 1. 1. 1.] (6,)
[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]] (6, 5)


Zero arrays
[1. 1. 1. 1. 1. 1.] (6,)
[[[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]

 [[0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]
  [0. 0. 0. 0.]]] (6, 5, 4)


In [33]:
#experment creating 4D array
zeros_np_4Darray = np.zeros((6,5,4,2))   #6=no.of rows of 4d arrays, 5=no.of rows of 2d array, 4=no.of rows of 2d array, 2= no.of columns of 2d array
print(zeros_np_4Darray, zeros_np_4Darray.shape)

[[[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]]


 [[[0. 0.]
   [0. 0.]
   [0. 0.]
   [0. 0.]]

  [[0. 0.]
   [0. 0.]
   [

# **Random Numbers**

In [40]:
random_np_3Darray=np.random.randn(4,5)
print(random_np_3Darray, random_np_3Darray.shape)

random_np_3DIntarray=np.random.randint(4,5)
print(random_np_3DIntarray, type(random_np_3DIntarray))

[[-1.24035111  1.02341302  1.44223976 -0.89199594  1.48976426]
 [-1.28942313  1.06528336 -0.7484188  -0.83958076 -1.18414878]
 [-0.70828923  0.66030161  0.3263614  -0.53302563  1.82236036]
 [-0.96220405  1.26427099  0.53453682  0.31630439 -0.28259055]] (4, 5)
4 <class 'int'>


#Next week ------
#Numpy Slicing , Reshaping, Matrix operations
